
    <? include_once $_SERVER['DOCUMENT_ROOT'] . "/Common/Include/Header.alt"; ?>
    <link rel="stylesheet" href="/Univ/Hongik/Common/css/hongik.css?1.1" />
    <script type="text/javascript" src="/Univ/Hongik/Common/js/top.js"></script>
    <link rel="stylesheet" href="/Univ/Hongik/coupon/css/coupon.css" />
  <body>
    <div class="coupon_wrapper">
      <? include_once $_SERVER['DOCUMENT_ROOT'] . "/Univ/Hongik/Common/top.phtml"; ?>
      <div class="coupon_add_wrapper">
        <table>
          <tr>
            <td rowspan="2" class="univ_main_tit">쿠폰 담기</td>
            <td class="univ_right_tit">
              보유 중인 쿠폰 : <span class="coupon_num">3</span>장
            </td>
          </tr>
          <tr>
            <td class="univ_right_tit">
              추가 가능 쿠폰 : <span class="coupon_num">2</span>장
            </td>
          </tr>
        </table>

        <div class="univ_search">
          <input type="text" placeholder="검색어를 입력해 주세요." />
        </div>

        <div class="coupon_add_div">
          <p class="coupon_list_sort">
            <!-- TODO : coupon_sort_on 클래스의 유무로 정렬이 바뀌도록 설정합니다. -->
            <span class="coupon_sort coupon_sort_on">최신 순</span> |
            <span class="coupon_sort">종료일 순</span> |
            <span class="coupon_sort">인기 순</span>
          </p>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
          <div class="coupon">
            <p class="coupon_nick">난쟁이가 쏘아올린 작은 알</p>
            <p class="coupon_title">무조건 10% 할인</p>
            <p class="coupon_date">~ <span>19.04.25</span> 까지</p>
          </div>
        </div>
      </div>
    </div>
    <? include $_SERVER["DOCUMENT_ROOT"] . "/Common/Include/MenuItem.alt" ?>
  </body>
</html>
